### ISSUE TITLE
hewo u did a oopsy woopsy

### ISSUE THREAD

**Issue by kevinn-t** [ohs-csclub/wildcat-runner#1]
glhf reading this

:(( da paws resets scowe uwu. pweez fix this (◕‿◕). daddy's dwinking his angy juice again, i gtg. c u later uwu. o/

 >:) IM BACK. i fink kitty ypos & yvel should reset afta spwattewing on the 3 ton twaffic cones T_T . sowy i haf to go agen. baibai \o

 owo hewo again no more compwaints i swea. im just cuwius how u made the backgwownd scwolling thing

Check out more of my uwu proficiency whenever I feel like automating this beauty.  ¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by jinkang-0** [comment]
Yes, hitting traffic cones and being reset by them is an intentional feature. The wildcat is very sensitive to them.
The background scrolling works by moving an image twice as wide as the width of the screen from right to left, setting it back to the rightmost position when it reaches the leftmost position.

I'm equally curious, did you use a translator to write that message?
